import SEO from '@/components/SEO';
import SchemaOrg from '@/components/SchemaOrg';

export default function Disclaimer() {
    return (
        <>
            <SEO
                title="Disclaimer"
                description="Legal disclaimer regarding the use of ColorVerse and its generated content."
                canonicalUrl="/disclaimer"
            />
            <SchemaOrg
                type="WebPage"
                data={{
                    "name": "Disclaimer",
                    "description": "The disclaimer for ColorVerse."
                }}
            />
            <div className="max-w-3xl mx-auto py-12 prose prose-slate">
                <h1 className="text-4xl font-extrabold text-gray-900 mb-8">Disclaimer</h1>
                <div className="space-y-6 text-gray-600 leading-relaxed">
                    <p>
                        The information provided by ColorVerse is for general informational purposes only. All information on the site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.
                    </p>
                    <h2 className="text-2xl font-bold text-gray-900 mt-10">External Links Disclaimer</h2>
                    <p>
                        The site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability or completeness by us.
                    </p>
                    <h2 className="text-2xl font-bold text-gray-900 mt-10">Design Usage</h2>
                    <p>
                        The CSS snippets, gradients, and colors generated by these tools are free to use in your personal or commercial projects. However, ColorVerse is not responsible for any issues arising from the implementation of these code snippets in your projects.
                    </p>
                </div>
            </div>
        </>
    );
}
